(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
(* LIRE: Lissajous-figure Reconstruction for nonlinear polarization tomography of bichromatic fields. *)
(* \[Copyright] Emilio Pisanty, 2019 *)

(* For more information,see https://github.com/episanty/LIRE *)


(* ::Input::Initialization:: *)
BeginPackage["LIRE`"];


(* ::Input::Initialization:: *)
$LIREversion::usage="$LIREversion prints the current version of the LIRE package in use and its timestamp.";
$LIREtimestamp::usage="$LIREtimestamp prints the timestamp of the current version of the LIRE package.";
Begin["`Private`"];
$LIREversion:="LIRE v1.0.0, "<>$LIREtimestamp;
End[];


(* ::Input::Initialization:: *)
Begin["`Private`"];
$LIREtimestamp="Sun 17 Mar 2019 00:19:21";
End[];


(* ::Input::Initialization:: *)
$LIREdirectory::usage="$LIREdirectory is the directory where the current LIRE package instance is located.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
With[{softLinkTestString=StringSplit[StringJoin[ReadList["! ls -la "<>StringReplace[$InputFileName,{" "->"\\ "}],String]]," -> "]},
If[Length[softLinkTestString]>1,(*Testing in case $InputFileName is a soft link to the actual directory.*)
$LIREdirectory=StringReplace[DirectoryName[softLinkTestString[[2]]],{" "->"\\ "}],
$LIREdirectory=StringReplace[DirectoryName[$InputFileName],{" "->"\\ "}];
]];
End[];


(* ::Input::Initialization:: *)
$LIREcommit::usage="$LIREcommit returns the git commit log at the location of the LIRE package if there is one.";
$LIREcommit::OS="$LIREcommit has only been tested on Linux.";


(* ::Input::Initialization:: *)
Begin["`Private`"];
$LIREcommit:=(If[$OperatingSystem!="Unix",Message[$LIREcommit::OS]];
StringJoin[Riffle[ReadList["!cd "<>$LIREdirectory<>" && git log -1",String],{"\n"}]]);
End[];


(* ::Input::Initialization:: *)
EndPackage[];


(* ::Input::Initialization:: *)
DistributeDefinitions["LIRE`"];
